#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UniversalImageLoaderSample.Resource", IsApplication=true)]

namespace UniversalImageLoaderSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_empty = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_error = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_stub = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int fragmentsButton = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int gallery = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int grid = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int image = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int imageGalleryButton = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int imageGridButton = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int imageListButton = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int imagePagerButton = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int image_left = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int image_right = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int item_clear_disc_cache = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int item_clear_memory_cache = 2131230735;
			
			// aapt resource value: 0x7f080012
			public const int item_pause_on_fling = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int item_pause_on_scroll = 2131230737;
			
			// aapt resource value: 0x7f08000c
			public const int loading = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int pager = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int pager_title_strip = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int progress = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int text = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ac_complex = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ac_home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fr_image_gallery = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fr_image_grid = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fr_image_list = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fr_image_pager = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_gallery_image = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int item_grid_image = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int item_list_image = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int item_pager_image = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int widget = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int ac_name_complex = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ac_name_image_gallery = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int ac_name_image_grid = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ac_name_image_list = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ac_name_image_pager = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int button_image_gallery = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int button_image_grid = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int button_image_list = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int button_image_pager = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int button_list_and_grid = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int descr_image = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int label_examples = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int menu_item_clear_disc_cache = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int menu_item_clear_memory_cache = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int menu_item_pause_on_fling = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int menu_item_pause_on_scroll = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int title_grid = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int title_list = 2131034124;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ProgressBarStyle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int widget_provider = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
